/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class Library {

    public static void main(String[] args) {
        System.out.println("==============");

        int[][] weeklyMonthTemperatures = {
                {2, 2, 2, 2, 2, 2, 2},
                {3, 3, 3, 3, 3, 3, 3},
                {4, 4, 4, 4, 4, 4, 4},
                {1, 1, 1, 1, 1, 1, 1},
        };

        System.out.println(Arrays.toString(matrixRowsAvg(weeklyMonthTemperatures)));
    }

    public static int[] roll(int n) {
        System.out.println("salah");
        int[] valuesOfRolling = new int[n];
        Random random = new Random();
        for (int i = 0; i < n; i++) {
            int rollValue = random.nextInt(6) + 1;
            valuesOfRolling[i] = rollValue;
        }
        return valuesOfRolling;
    }

    public static boolean containsDuplicates(int array[]) {
        boolean checker = false;
        for (int i = 0; i < array.length; i++) {
            for (int j = i + 1; j < array.length; j++) {
                if (array[i] == array[j]) {
                    checker = true;
                }
            }
        }
        return checker;
    }

    public static int calculatingAverages(int array[]) {
        int sum = 0;
        for (int i = 0; i < array.length; i++) {
            sum += array[i];
        }
        int average = sum / array.length;
        return average;
    }

    public static int[] matrixRowsAvg(int[][] matrix) {
        int arrayOfAvgRows[] = new int[matrix.length];
        for (int i = 0; i < matrix.length; i++) {
            arrayOfAvgRows[i] = calculatingAverages(matrix[i]);
        }
        int smallestRowAvgIndex = arrayOfAvgRows[0];
        for (int j = 0; j < matrix.length; j++) {
            if (smallestRowAvgIndex > arrayOfAvgRows[j]) {
                smallestRowAvgIndex = j;
            }
        }
        return matrix[smallestRowAvgIndex];
    }
}
