/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String [] args) {
        Restaurant restaurant1 = new Restaurant("Burgeriz",5,"$$");
        restaurant1.addReview("Amazing food, bad for health", "Burgeriz", "Salah", 5, "$$$");
        String result =restaurant1.toString();


    }
    public boolean someLibraryMethod() {
        return true;
    }
}
