/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Library {
    public static String readJS(String fullPath) throws FileNotFoundException {
        String missingCol = "";
        int line = 1;
        File path = new File(fullPath);
        Scanner reader = new Scanner(path);
        while (reader.hasNextLine()) {
            String oneLine = reader.nextLine();
            if (!oneLine.endsWith(";") && !oneLine.endsWith("{") && !oneLine.endsWith("}") && !oneLine.contains("if") && !oneLine.contains("else") && !oneLine.equals("")) {
                missingCol = "Line " + line + ": Missing semicolon.\n"+missingCol;

            }
            line += 1;
        }
        System.out.println(missingCol);

        return missingCol;
    }

    public static void main(String[] args) throws FileNotFoundException {
        readJS("lib/src/main/resources/gates.js");
    }
}

