/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
//    @Test
//    public void testRestaurantAddReview() {
//        Restaurant burgerizz = new Restaurant("burgerizz", 5);
//        Review salah = new Review("It's amazing", "salah", 5);
//        burgerizz.addReview(salah);
//        Review rami = new Review("I don't like it", "rami", 1);
//        burgerizz.addReview(rami);
//        String expected="Restaurant{stars=3.0, price=5$, name='burgerizz'}";
//        String actual=burgerizz.toString();
//        assertEquals(expected,actual);
//    }
//
//    @Test
//    public void testRestaurantInstance() {
//        Restaurant burgerizz = new Restaurant("burgerizz", 5);
//        String expected="Restaurant{stars=0.0, price=5$, name='burgerizz'}";
//        String actual=burgerizz.toString();
//        assertEquals(expected,actual);
//    }
//
//    @Test
//    public void testReviewInstance() {
//        Review salah = new Review("It's amazing", "salah", 5);
//        String expected="Review{body='It's amazing', author='salah', stars=5}";
//        String actual=salah.toString();
//        assertEquals(expected,actual);
//    }


}
